# The directory from which notification templates are read.
templates:
- '/etc/alertmanager/template/*.tmpl'

# The root route on which each incoming alert enters.
route:
  # The labels by which incoming alerts are grouped together. For example,
  # multiple alerts coming in for cluster=A and alertname=LatencyHigh would
  # be batched into a single group.
  group_by: ['alertname']

  # When a new group of alerts is created by an incoming alert, wait at least
  # 'group_wait' to send the initial notification.  This way ensures that you
  # get multiple alerts for the same group that start firing shortly after
  # another are batched together on the first notification.
  group_wait: 5m

  # When the first notification was sent, wait 'group_interval' to send a batch
  # of new alerts that started firing for that group.
  group_interval: 2m

  # If an alert has successfully been sent, wait 'repeat_interval' to
  # resend them.
  repeat_interval: 12h

  # A default receiver
  receiver: skiabot

  # All the above attributes are inherited by all child routes and can
  # overwritten on each.

  # The child route trees.
  routes:
  - match:
      specialroute: android
    receiver: android
  - match:
      category: general
    receiver: general

# Inhibition rules allow to mute a set of alerts given that another alert is
# firing. We use this to mute any warning-level notifications if the same
# alert is already critical.
inhibit_rules:
- source_match:
    severity: 'critical'
  target_match:
    severity: 'warning'
  # Apply inhibition if the alertname is the same.
  equal: ['alertname']


receivers:
- name: 'skiabot'
  webhook_configs:
    - url: 'http://localhost:8004/chat?room=skiabot_alerts'

- name: 'general'
  webhook_configs:
    - url: 'http://localhost:8004/chat?room=general_alerts'

- name: 'android'
  webhook_configs:
    - url: 'http://localhost:8004/email?email=skia-android@google.com'

