global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
      - targets:
        - localhost:8001
        - localhost:9000

rule_files:
  - "alert.rules"
  - "absent.rules"

scrape_configs:
  - job_name: 'android_compile'
    static_configs:
      - targets: ['android-compile:20000']

  - job_name: 'androidingest'
    static_configs:
      - targets: ['skia-android-ingest:20000']

  - job_name: 'android-master-ingest'
    static_configs:
      - targets: ['skia-android-ingest:20001']

  - job_name: 'autoroll-be'
    static_configs:
      - targets: ['afdo-chromium-autoroll:20000']
      - targets: ['android-master-autoroll:20000']
      - targets: ['android-next-autoroll:20000']
      - targets: ['android-o-autoroll:20000']
      - targets: ['flutter-engine-flutter-autoroll:20000']
      - targets: ['fuchsia-autoroll:20000']
      - targets: ['skia-flutter-autoroll:20000']

  - job_name: 'collectd'
    static_configs:
      - targets: ['skia-monitoring:20002']

  - job_name: 'corpproxy'
    static_configs:
      - targets: ['skia-proxy:20000']

  - job_name: 'ct_pixel_diff'
    static_configs:
      - targets: ['skia-ct-pixel-diff:20000']

  - job_name: 'datahopper'
    static_configs:
      - targets: ['skia-datahopper2:20000']

  - job_name: 'diffserver-prod'
    static_configs:
      - targets: ['skia-diffserver-prod:20000']

  - job_name: 'diffserver-stage'
    static_configs:
      - targets: ['skia-diffserver-stage:20000']

  - job_name: 'fuzzer-fe'
    static_configs:
      - targets: ['skia-fuzzer-fe:20000']

  - job_name: 'skiacorrectness-pdfium'
    static_configs:
      - targets: ['skia-gold-pdfium:20001']

  - job_name: 'skiacorrectness-prod'
    static_configs:
      - targets: ['skia-gold-prod:20001']

  - job_name: 'skiacorrectness-stage'
    static_configs:
      - targets: ['skia-gold-stage:20001']

  - job_name: 'skiacorrectness-public'
    static_configs:
      - targets: ['skia-gold-public:20001']

  - job_name: 'chromevr_gold_ingestion'
    static_configs:
      - targets: ['skia-ingestion:20002']
        labels:
          corpus: chromevr_gold

  - job_name: 'gold_ingestion'
    static_configs:
      - targets: ['skia-ingestion:20000']
        labels:
          corpus: gold

  - job_name: 'pdfium_gold_ingestion'
    static_configs:
      - targets: ['skia-ingestion:20001']
        labels:
          corpus: pdfium_gold

  - job_name: 'logmetrics'
    static_configs:
      - targets: ['skia-monitoring:20001']

  - job_name: 'probeserver'
    static_configs:
      - targets: ['skia-monitoring:20000']

  - job_name: 'datastore_backup'
    static_configs:
      - targets: ['skia-monitoring:20005']

  - job_name: 'alert-to-pubsub'
    static_configs:
      - targets: ['skia-prom:20007']

  - job_name: 'push'
    static_configs:
      - targets: ['skia-push:20000']

  - job_name: 'skiaperf'
    static_configs:
      - targets: ['skia-perf:20000']
      - targets: ['skia-android-perf:20000']
        labels:
          subdomain: android-perf
      - targets: ['skia-android-master-perf:20000']
        labels:
          subdomain: android-master-perf

  - job_name: 'status'
    static_configs:
      - targets: ['skia-status:20000']
      - targets: ['skia-status-internal:20000']

  - job_name: 'swarming_logger'
    static_configs:
      - targets: ['skia-swarming-logger:20000']

  - job_name: 'task_scheduler'
    static_configs:
      - targets: ['skia-task-scheduler:20000']
      - targets: ['skia-task-scheduler-internal:20000']

  - job_name: 'chromevr_gold_traceserver'
    static_configs:
      - targets: ['skia-tracedb:20005']
        labels:
          corpus: chromevr_gold

  - job_name: 'gold_traceserver'
    static_configs:
      - targets: ['skia-tracedb:20004']
        labels:
          corpus: gold

  - job_name: 'pdfium_gold_traceserver'
    static_configs:
      - targets: ['skia-tracedb:20003']
        labels:
          corpus: pdfium_gold

# pulld for every server.
  - job_name: 'pulld'
    static_configs:
      - targets: ['afdo-chromium-autoroll:11000']
      - targets: ['android-master-autoroll:11000']
      - targets: ['android-next-autoroll:11000']
      - targets: ['android-o-autoroll:11000']
      - targets: ['flutter-engine-flutter-autoroll:11000']
      - targets: ['fuchsia-autoroll:11000']
      - targets: ['skia-android-ingest:11000']
      - targets: ['skia-android-master-perf:11000']
      - targets: ['skia-android-perf:11000']
      - targets: ['skia-ct-pixel-diff:11000']
      - targets: ['skia-datahopper2:11000']
      - targets: ['skia-diffserver-prod:11000']
      - targets: ['skia-diffserver-stage:11000']
      - targets: ['skia-flutter-autoroll:11000']
      - targets: ['skia-fuzzer-fe:11000']
      - targets: ['skia-gold-pdfium:11000']
      - targets: ['skia-gold-prod:11000']
      - targets: ['skia-internal:11000']
      - targets: ['skia-monitoring:11000']
      - targets: ['skia-monitoring:11000']
      - targets: ['skia-perf:11000']
      - targets: ['skia-prom:11000']
      - targets: ['skia-proxy:11000']
      - targets: ['skia-push:11000']
      - targets: ['skia-skfe-1:11000']
      - targets: ['skia-skfe-2:11000']
      - targets: ['skia-status:11000']
      - targets: ['skia-swarming-logger:11000']
      - targets: ['skia-task-scheduler-internal:11000']
      - targets: ['skia-task-scheduler:11000']
      - targets: ['skia-tracedb:11000']

  # Prometheus self monitoring.
  - job_name: 'prometheus'
    static_configs:
      - targets: ['skia-prom:8000']

  - job_name: 'alertmanager'
    static_configs:
      - targets: ['skia-prom:8001']

  - job_name: 'proxy_with_auth'
    static_configs:
      - targets: ['skia-prom:20002']

  - job_name: 'alert_proxy_with_auth'
    static_configs:
      - targets: ['skia-prom:20003']

  - job_name: 'webhook_proxy'
    static_configs:
      - targets: ['skia-prom:20004']

  # Gateways
  - job_name: 'pushgateway'
    honor_labels: true
    static_configs:
      - targets: ['localhost:20006']

  # Federation
  - job_name: 'federate'
    scrape_interval: 30s

    honor_labels: true
    metrics_path: '/federate'

    params:
      'match[]':
        - '{job=~".+"}'

    static_configs:
      - targets:
        - 'localhost:12001'
        labels:
          federated: 'jumphost-rpi-01'
      - targets:
        - 'localhost:12002'
        labels:
          federated: 'jumphost-linux-01'
      - targets:
        - 'localhost:12003'
        labels:
          federated: 'jumphost-win-02'
      - targets:
        - 'localhost:12004'
        labels:
          federated: 'jumphost-win-03'
      - targets:
        - 'localhost:12005'
        labels:
          federated: 'jumphost-internal-01'
