# tasks file for install_metadata_server

- name: Load metadata_server_ansible executables.
  run_once: yes
  include_role:
    name: get_ansible_binaries
  vars:
    get_ansible_binaries_application: metadata_server_ansible
    get_ansible_binaries_version: '{{ metadata_server_ansible_version }}'

- name: Copy over service file.
  become: yes
  template:
    src: templates/metadata_server_ansible.service
    dest: /etc/systemd/system/metadata_server_ansible.service
    owner: root
    group: root
    mode: '0644'

- name: Copy over executable.
  become: yes
  copy:
    src:
      "{{ get_ansible_binaries_directory.path }}/build/{{
      ansible_facts['system'] }}/{{ ansible_facts['architecture'] }}/{{
      install_metadata_server__service_account_name }}/metadata_server_ansible"
    dest: /usr/local/bin/metadata_server_ansible
    owner: root
    group: root
    mode: '0755'

- name: Start systemd servce.
  become: yes
  systemd:
    enabled: yes
    state: restarted
    name: metadata_server_ansible
    daemon_reload: yes
