---
# tasks file for install_metadata_server

- name: make temporary directory for secrets and trigger `clean_up_tempfile`
  delegate_to: 127.0.0.1
  tempfile:
    state: directory
  register: secrets_dir
  notify: clean_up_tempfile

- name: set service account key location fact
  set_fact:
    service_account_key_filename: '{{ secrets_dir.path }}/key.json'

- name: Extract service account key
  delegate_to: 127.0.0.1
  command:
    argv:
      - '{{ all.repo_root }}/kube/secrets/get-secret-at-path.sh'
      - etc
      - '{{ install_metadata_server.service_account_name }}'
      - '.data."key.json"'
      - '{{ service_account_key_filename }}'
    creates: '{{ service_account_key_filename }}'

- name:
    Build metadata_server_ansible for the target machine with the service
    account key embedded.
  delegate_to: 127.0.0.1
  make:
    chdir: '{{ all.repo_root }}/skolo/'
    target:
      "build_metadata_server_ansible_{{ ansible_facts['architecture'] }}_{{
      ansible_facts['system'] }}_{{ install_metadata_server.service_account_name
      }}"
    params:
      # Pass the service account key base64 encoded so it doesn't mess up the Go compile command line.
      SERVICE_ACCOUNT_KEY:
        "{{ lookup('file', service_account_key_filename) | b64encode }}"

- name: Copy over service file.
  become: yes
  template:
    src: templates/metadata_server_ansible.service
    dest: /etc/systemd/system/metadata_server_ansible.service
    owner: root
    group: root
    mode: '0644'

- name: Copy over executable.
  become: yes
  copy:
    src:
      "{{ all.repo_root }}/skolo/build/{{ ansible_facts['system'] }}/{{
      ansible_facts['architecture'] }}/{{
      install_metadata_server.service_account_name }}/metadata_server_ansible"
    dest: /usr/local/bin/metadata_server_ansible
    owner: root
    group: root
    mode: '0755'

- name: Start systemd servce.
  become: yes
  systemd:
    enabled: yes
    state: restarted
    name: metadata_server_ansible
    daemon_reload: yes
