---
- name: Create chrome-bot user for linux
  import_tasks: linux.yml
  when: ansible_facts['system']|lower == "linux"

- name: Other platforms
  fail:
    msg: This system isn't supported, please add support.
  when: ansible_facts['system']|lower != "linux"
