- name: Install selenium.
  block:
    - name: Pick temp filename to hold requirements.
      tempfile:
      register: requirements
    - name: Overwrite temp file with requirments.
      copy:
        src: files/selenium_requirements.txt
        dest: '{{ requirements.path }}'
        mode: 0600
        force: yes
    - name: Run pip against requirements.
      pip:
        # Dodge /usr/bin/pip3, which triggers an xcode-select interruption.
        executable: /usr/local/bin/pip3
        requirements: '{{ requirements.path }}'

- name: Copy over executable.
  become: yes
  copy:
    src:
      "{{ get_ansible_binaries_directory.path }}/build/{{
      ansible_facts['system'] }}/{{ ansible_facts['architecture']
      }}/comp-ui-cron-job"
    dest: /usr/local/bin/comp-ui-cron-job
    owner: root
    group: wheel
    mode: 0755

- name: Launch comp-ui-cron-job once a day.
  vars:
    launch_agents_folder: ~{{ skolo_account }}/Library/LaunchAgents
    compui_launchd_plist: '{{ launch_agents_folder }}/org.skia.compui.plist'
  block:
    - name: Make sure LaunchAgents folder is there.
      file:
        path: '{{ launch_agents_folder }}'
        state: directory
        owner: '{{ skolo_account }}'
        group: '{{ skolo_group }}'
        mode: 0755

    - name: Install startup job.
      copy:
        src: files/org.skia.compui.plist
        dest: '{{ compui_launchd_plist }}'
        owner: '{{ skolo_account }}'
        group: '{{ skolo_group }}'
        # 0660 required according to https://developer.apple.com/library/archive/documentation/MacOSX/Conceptual/BPSystemStartup/Chapters/CreatingLaunchdJobs.html:
        mode: 0600

    - name: Find chrome-bot user id.
      command: id -u
      register: chromebot_uid

    - name: Have launchd unload the existing service.
      become:
      ignore_errors: yes
      command: launchctl bootout gui/{{ chromebot_uid.stdout }}/org.skia.compui

    - name: Have launchd start comp-ui-cron-job.
      become:
      command:
        launchctl bootstrap gui/{{ chromebot_uid.stdout }} {{
        compui_launchd_plist }}
