# Does the absolute minimum for an RPI with an SD card that's been configured
# via //infra/skolo/rasperry-pi/switchboard/configure-image.sh
#
# Once this is run then the 'rpi.yml' playbook can be run to finish/update the
# machine.
- hosts: '{{ variable_hosts }}'
  user: root
  gather_facts: no

  pre_tasks:
    # First install python3 so we can use more issue more than 'raw' commands.
    - name: install python3
      raw:
        'apt update && apt -y install sudo python3 python3-apt python3-distutils'

    # We can gather facts now that python3 is installed.
    # Needed for create_chrome_bot_user.
    - name: gather facts
      setup:

  roles:
    - set_root_password
    - create_chrome_bot_user
    - copy_authorized_keys
