# Configures metrics and alerting on each jumphost.
#
# A slimmed down playbook that just deals with Prometheus and alert_to_pubsub.
#
# The primary jumphost playbook is jumphosts.yaml.
- hosts: jumphosts
  user: chrome-bot
  gather_facts: true
  vars:
    alert_to_pubsub_ansible_version_override: ''

  roles:
    - role: install_prometheus_and_alert_to_pubsub
      alert_to_pubsub_ansible_version:
        '{{ alert_to_pubsub_ansible_version_override }}'
