# Configures an RPi with everything it needs to run under switchboard.
- hosts: switchboard_rpis
  user: chrome-bot
  gather_facts: yes
  vars:
    test_machine_monitor_version_override: ''

  # Using the `roles:` key here causes an error about
  # test_machine_monitor_version being undefined in get_ansible_binaries during
  # install_test_machine_monitor.
  tasks:
    - import_role:
        name: copy_authorized_keys
    - import_role:
        name: copy_adbkey
    - import_role:
        name: copy_service_account_key
    - import_role:
        name: install_collectd
    - import_role:
        name: swarming_needs
    - import_role:
        name: switchboard_needs
    - import_role:
        name: install_test_machine_monitor
      vars:
        test_machine_monitor_version: '{{ test_machine_monitor_version_override }}'
