argument_specs:
  main:
    short_description:
      The main entry point for the install_test_machine_monitor role.
    options:
      test_machine_monitor_version:
        type: 'string'
        required: false
        default: ''
        description:
          'The version of test_machine_monitor to deploy, e.g.
          2021-09-17T22:47:32Z-jcgregorio-77033a142afc2ebf670339c958cbb4eb738c88ee-dirty'
