# Do all the things to set up a Skolo bot.
# Machine settings.
- import_playbook: skolo-settings.yml
# Install Python.
- import_playbook: python.yml
# Prep for Swarming.
- import_playbook: swarming-bot-settings.yml
- import_playbook: ../../common/ansible/skolo-credentials.yml
# Start Swarming. Must be last, since the bot will start running tasks after this.
- import_playbook: ../../common/ansible/bootstrap-swarming.yml
