# Set up the machine to run our tests.
- hosts: all
  remote_user: chrome-bot
  become: yes

  tasks:
  - name: Setup caffeinated.
    copy:
      src: ../org.skia.caffeinated.plist
      dest: /Library/LaunchAgents/
