argument_specs:
  main:
    short_description:
      The main entry point for the install_powercycle_server role.
    options:
      powercycle_server_ansible_version:
        type: "str"
        required: false
        default: ""
        description:
          'The version of powercycle_server_ansible to deploy, e.g.
          2021-09-17T22:47:32Z-jcgregorio-77033a142afc2ebf670339c958cbb4eb738c88ee-dirty'
