---
# Install Intel Graphics Driver for Skylake and later GPUs; applies only to group "skylake".
- hosts: skylake
  tasks:
  - name: Create Temp
    win_file:
      path: c:\Temp
      state: directory
  # The Intel driver uses the same product_id for multiple versions, so win_package doesn't work.
  - name: Copy the Intel Graphics Driver EXE to the host
    win_copy:
      src: "{{ win_package_src }}/Intel Graphics Skylake dch_win64_25.20.100.6444.exe"
      dest: c:\Temp\intel_gfx.exe
  - name: Install Intel Graphics Driver for Skylake and later
    # See https://www.intel.com/content/www/us/en/support/articles/000006773/graphics-drivers.html
    # The "-overwrite" option allows downgrading the driver if a newer one is already installed for
    # some reason (e.g. Windows Update).
    win_command: c:\Temp\intel_gfx.exe -s -A -overwrite -s
  - name: Cleanup
    win_file:
      path: c:\Temp\intel_gfx.exe
      state: absent
