apiVersion: v1
clusters:
  - cluster:
      certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURLakNDQWhLZ0F3SUJBZ0lRR0E4bmFUY0dmb1VlbEpNR0FUUGthVEFOQmdrcWhraUc5dzBCQVFzRkFEQXYKTVMwd0t3WURWUVFERXlRME9ERTFZbUpqTXkwNFpXSTRMVFEzTXpZdFlURXdaaTAxTlRkbU5qTXdNbUZpTlRndwpIaGNOTWpFd05ESXdNVGd6TmpJMFdoY05Nall3TkRFNU1Ua3pOakkwV2pBdk1TMHdLd1lEVlFRREV5UTBPREUxClltSmpNeTA0WldJNExUUTNNell0WVRFd1ppMDFOVGRtTmpNd01tRmlOVGd3Z2dFaU1BMEdDU3FHU0liM0RRRUIKQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUUNPRkM2L3VZcjdKUFFuNjEyL0FJUjRoaVd3MnMxRUhxZThkZ3pGNXliMQpycEVuMW1vbHNOblpzRGgyeTZiUWN2QkY4elNXOVR4ajdpc095TlJiczNLTGhPcVdIUDloT1RyU2JWaXRPZGIzCk03cXdGV3hBemxkaGhzTCszVDVjUTJBeURYa1RiZzNvLzhjOTZENkJ4SkhqWHdCRHQ1T3d0S3RJQXFCVEk5SnQKV2pnOWJMVzB2UmNLQm1KWk9BL2dYcHh5UExuRDFIWWJLc2hYRkJlUWJNOVVNbjVHd0VXMTgxQ3lHSkxsUFBmNgpCdEtWVlJybTVCTGtIZW9WTFpEdFYyTVBqZFZwdHFPZlhpYTZiYk1UNDVwaEY0NklPTDZwWGFtVUtBVGlFR0lNCmtEWSt3SUI2TTVGcDExbGhCNmN6WWFkMC8xRCs5b1h3VGg1Ly9rSkhyTWs5QWdNQkFBR2pRakJBTUE0R0ExVWQKRHdFQi93UUVBd0lDQkRBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJRbnIrR1FPNm4rZGk5bgp1b0FHL29SWDg2MHBuREFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBQ1FWMzNGcWF4dTNqWVp6N3NCaEk1YmdsCm9ySHBKZnBKWUtoMjArUUlNWW9OL0V3L0RQY0hZdDhEQ0x5bnd4ck9aYjFtVEE5Q3VJU3JoTlVHYVgyRE9NWHkKRmRBNEtqK1BOZHdyRTBIUUFORDU2d2hBWTNjSlNtQ0NPL1kvRzFYYVhSRUdtb1E3R1dUN3RRZVYvMFFVTE8wRAp2T3BpNFMzUjZlc2U4NzZHQUJmYzZWTjNRVDdGaGVDcVZuTEx1YmZ5S3ZnaUx5SWg3cmd4VmhkWkZNQ1FOWEFWCnFWM1cxOUYrNWRNMUVDQ0FhMkJ1M2FyMktCaE5zYVQ4eFFkOStTMDU4WTZXNTBxSDl6WldvOVphb0VjOG5wNU8KQWFWVjM1VTFMUlRlVVJFQUhMUGc2ZjhlN1JTY08wek5aWUhka0EvNmorc1hOeVJGME1xdUtPOUw2OG1JS0E9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
      server: https://35.202.226.23
    name: cluster-1
contexts:
  - context:
      cluster: cluster-1
      user: user-1
    name: my-cluster
current-context: my-cluster
kind: Config
preferences: {}
users:
  - name: user-1
    user:
      auth-provider:
        config:
        name: gcp
