argument_specs:
  main:
    short_description:
      The main entry point for the install_prometheus_and_alert_to_pubsub role.
    options:
      alert_to_pubsub_ansible_version:
        type: 'string'
        required: false
        default: ''
        description:
          'The version of alert_to_pubsub_ansible to deploy, e.g.
          2021-09-17T22:47:32Z-jcgregorio-77033a142afc2ebf670339c958cbb4eb738c88ee-dirty'
